### ISSUE TITLE
Build Error (Win7x64, Node v8.7.0, NPM v5.4.2, GYP v3.6.2)

### ISSUE THREAD

**Issue by Kruithne** [magiclen/node-int32#1]
Hey,

Upon running `npm install int32 --save` to install this module, the build process hits three errors as displayed below.

```
..\src\int32.c(225): error C2057: expected constant expression [D:\web\html\jenkins96\node_modules\int32\build\int32.vcxproj]
..\src\int32.c(225): error C2466: cannot allocate an array of constant size 0 [D:\web\html\jenkins96\node_modules\int32\build\int32.vcxproj]
..\src\int32.c(225): error C2133: 'a': unknown size [D:\web\html\jenkins96\node_modules\int32\build\int32.vcxproj]
```

Any assistance or insight on solving this would be greatly appreciated.

*P.S: Do you have any intention of adding support for common bitwise operations such as `AND` / `OR`?*

**Comment by magiclen** [comment]
Thank you. I've updated a new version (2.4.1). Please try it again.

I think it is easy to do bitwise operations in JavaScript level. Could you explain why you want to do these via N-API?

**Comment by Kruithne** [comment]
Thanks for the swift fix, it's building now.

I wasn't thinking straight with the bitwise and assumed it wouldn't allow operations the same way some bignumber libraries don't, but now that I've hooked it up it works fine.

Is it (or could it be) possible to restrict to unsigned values? Implementing a rather archaic hashing algorithm and it uses magic values such as `0xdeadbeef` but expects them to be the unsigned value of `3735928559` rather than the signed value of `-559038737`.

Thanks again, big help!

**Comment by magiclen** [comment]
If you want to get a 32-bit unsigned value from a signed value, you can just add 0x100000000 when the signed value is negative.

Because these are very tiny operations, it can be done quickly in JavaScript level. I don't suggest do these operations via N-API. It has some overhead to switch between the JavaScript and N-API levels. If you have heavy computations which are needed to be implement on Node.js, perhaps it is better to fully write them in C programs and use them through N-API.

**Comment by Kruithne** [comment]
Thanks, good call. I wasn't aware of the overhead, I'll try to need N-API calls to a minimum where possible. This won't be used for any performance sensitive environments.

One last thing, is this an issue with the library or my own common sense:
```
let a = new Int32(3735954792);
a.getValue();
// -> -559153152 (Correct so far)

a.shiftRight(18);
a.getValue();
// -> -2133 (Expected 14251)?
```

I'm not sure what I'm missing with the shift there. Testing it out of JS and with a calculator, I expect 14251 as the result.

**Comment by magiclen** [comment]
3735954792=0xDEAE2568=0b11011110101011100010010101101000
0b11011110101011100010010101101000 >> 18 = 0b11111111111111111111011110101011

0b11111111111111111111011110101011 the MSB is 1, which means it is nagative
Then, compute its 2's complement, that is 0b00000000000000000000000001010101 = 2133
So, the value -2133 was correct.

The value 14251 you expected should be from a unsigned right-shift operation instead of a signed right-shift operation. You can simply get the value by using the method **shiftRightUnsigned**.

**Comment by Kruithne** [comment]
Aha, I hadn't noticed the `shiftRightUnsigned` function, that'll teach me to skip over documentation. Thanks again for your help!

I've managed to hoggle together a working implementation of the hashing algorithm I was after in Node, although the code is a bit of hogwash. But, it produces the expected output now, even if it is a mess.

https://github.com/Kruithne/node-jenkins96

Thanks!

**Comment by magiclen** [comment]
Ha, you are welcome.

At line 29 in your jenkins96.js,

    _restrict(int32.shiftLeft(a, b)) | _restrict(int32.shiftRightUnsigned(a, 32 - b))

it can be reduced to,

    int32.rotateLeft(a, b)

I think this algorithm can be easier to implement by using N-API. And the performance will be much better.

**Comment by Kruithne** [comment]
Added that change in, thanks.

As for implementing a native solution via N-API, I thought about doing it, but my experience with C is somewhat too limited for me to take a crack at it myself.
